-- +goose Up
CREATE TABLE users (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(255) NOT NULL UNIQUE -- username VARCHAR(50) NOT NULL UNIQUE,
    -- password_hash VARCHAR(255) NOT NULL,
);

-- +goose Down
DROP TABLE users;